Transform0:
  from: "base_link"
  to: "base_footprint"
  translation_x_y_z: [0.0, 0.0, 0.0]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]

Transform1:
  from: "base_footprint"
  to: "bev"
  translation_x_y_z: [0.0, 0.0, 2.0]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]

Transform2:
  from: "base_footprint"
  to: "frontcenter"
  translation_x_y_z: [2.0, 0.0, 1.4]
  rotation_yaw_pitch_roll: [0.0, -5.0, 0.0]
